[package]
name = "py-op"
version = "0.2.0"
repository = "https://github.com/atolab/zenoh-flow-examples"
homepage = "http://zenoh.io"
authors = ["kydos <angelo@icorsaro.net>",
           "gabrik <gabriele.baldoni@gmail.com>",
           "Julien Loudet <julien.loudet@adlinktech.com>",]
edition = "2018"
license = " EPL-2.0 OR Apache-2.0"
categories = ["network-programming"]
description = "Zenoh Flow Examples"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zenoh-flow = { git = "https://github.com/eclipse-zenoh/zenoh-flow.git", branch = "master"}
zenoh-flow-python-types = {path = "../zenoh-flow-python-types/"}
pyo3 = "0.15"

log = "0.4"
libloading = "0.7"

[build-dependencies]
pyo3-build-config = {version = "0.15", features = ["resolve-config"]}

[features]
abi-py36 = ["pyo3/abi3-py36"]
default = ["abi-py36"]

[lib]
name = "py_op"
crate-type=["cdylib"]
path="src/lib.rs"

